%% Define plots in figure

%%% axes to hold original data 
	axDataLeft = axes('Parent',figHandle,...
		'Position',[.1 .4 .1 .5],...
		'Tag', 'axDataLeft',...
		'NextPlot','replace');
	axDataBottom = axes('Parent',figHandle,...
		'Position',[.215 .31 .75 .075],...
		'Tag', 'axDataBottom',...
		'NextPlot','replace');

	% must be last, otherwise imagesc screws up
	axRP = axes('Parent',figHandle,...
		'Position',[.215 .4 .75 .5],...
		'Tag', 'axDataRP',...
		'NextPlot','replace',...
		'YTick',[],...
		'XTick',[]);

%% fields to hold the parameters
buttons = uibuttongroup('Position', [.34 .05 .3 .15],...
	'visible','on');

	textDim = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.1 .7 .6 .2],...
		'BackgroundColor',  [0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Dimension:',...
		'Visible','on',...
		'Tooltip','The dimension is the number of points forming the OPs');

	valDim = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.75 .7 .2 .2],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(dim),...
		'Visible','on',...
		'Tooltip','Insert the Dimension (2-13)',...
		'Tag','valDim');	

	textTau = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.1 .4 .6 .2],...
		'BackgroundColor',  [0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Delay :',...
		'Visible','on',...
		'Tooltip','The delay is the distance between the points forming the OPs');

	valTau = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.75 .4 .2 .2],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(tau),...
		'Visible','on',...
		'Tooltip','Insert the Delay',...
		'Tag','valTau');

	textSymbolise = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.1 .1 .6 .2],...
		'BackgroundColor',  [0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Colourise?',...
		'Visible','on',...
		'Tooltip','Maps the recurrent symbols to colours aka Symbol-RP');

	valSymbolise = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.8 .125 .2 .2],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','checkbox',... 
		'Visible','on',...
		'Tooltip','Check to plot colourised symbol plot',...
		'Tag','valSymbolise');

%% define the Buttons

	buttonEst = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.65 .15 .15 .05],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Estimate',...
		'Visible','on',...
		'Tooltip','Estimate embedding delay', ...
		'Callback',{@buttonEstCallback,X,Y});

	buttonStore = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.65 .1 .15 .05],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Store',...
		'Visible','on', ...
		'Tooltip','Store the (Cross) Recurrence Plot in the workspace',...
		'Callback',{@buttonStoreCallback});

	buttonClose = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.65 .05 .15 .05],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Close',...
		'Visible','on', ...
		'Tooltip','Close the OPCRP GUI',...
		'Callback',{@buttonCloseCallback});

	buttonCompute = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.8 .05 .15 .15],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Compute',...
		'Visible','on',...
		'Tooltip','Compute the (Cross) Recurrence Plot', ...
		'Callback',{@buttonComputeCallback,X,Y});

%% hardcore fancying
dateString = date;

	textNLD = uicontrol('Parent',figHandle,...
		'Units', 'normalized', ...
		'Position',[.01 .01 .3 .2],...
		'Style','text',... 
		'BackgroundColor',[.801 .75 .688], ... 
		'Tag', 'NLD ',...
		'FontSize',9,...
		'String',sprintf('Nonlinear\nDynamics\nGroup\n\nUniversity of Potsdam\n(c) 2007-%s',dateString(end-1:end)),...
		'ToolTip','The Nonlinear Dynamics Group http://www.agnld.uni-potsdam.de');

	textTitel = uicontrol('Parent',figHandle,...
		'Units', 'normalized', ...
		'Position',[.1 .93 .8 .05],...
		'Style','text',... 
		'BackgroundColor',[.801 .75 .688], ... 
		'Tag', 'title',...
		'String','Order Patterns Recurrence Plot GUI',...
		'FontSize',12,...
		'FontWeight','bold');

%%% align elements
align([textDim,valDim],'VerticalAlignment','Bottom')
align([textTau,valTau],'VerticalAlignment','Bottom')
