%%%%%%%%%%%%%%%%%%%%%%%
%			Define axes			%
%%%%%%%%%%%%%%%%%%%%%%%

axData = axes('Parent',fHandle,...
	'Position',[.05 .85 .44 .1],...
	'Tag','axData',...
	'NextPlot','replace',...
	'Box','on');

axOP = axes('Parent',fHandle,...
	'Position',[.51 .85 .44 .10],...
	'Tag','axOP',...
	'NextPlot','replace',...
	'Box','on');

axRR = axes('Parent',fHandle,...
	'Position',[.05 .695 .44 .1],...
	'Tag','axRR',...
	'NextPlot','replace',...
	'Box','on');

axDET = axes('Parent',fHandle,...
	'Position',[.51 .695 .44 .1],...
	'Tag','axDET',...
	'NextPlot','replace',...
	'Box','on');	

axL = axes('Parent',fHandle,...
	'Position',[.05 .555 .44 .1],...
	'Tag','axL',...
	'NextPlot','replace',...
	'Box','on');

axLmax = axes('Parent',fHandle,...
	'Position',[.51 .555 .44 .1],...
	'Tag','axLmax',...
	'NextPlot','replace',...
	'Box','on');	

axENT = axes('Parent',fHandle,...
	'Position',[.05 .415 .44 .1],...
	'Tag','axENT',...
	'NextPlot','replace',...
	'Box','on');

axLAM = axes('Parent',fHandle,...
	'Position',[.51 .415 .44 .1],...
	'Tag','axLAM',...
	'NextPlot','replace',...
	'Box','on');	

axTT = axes('Parent',fHandle,...
	'Position',[.05 .275 .44 .1],...
	'Tag','axTT',...
	'NextPlot','replace',...
	'Box','on');

axVmax = axes('Parent',fHandle,...
	'Position',[.51 .275 .44 .1],...
	'Tag','axVmax',...
	'NextPlot','replace',...
	'Box','on');	
	
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			Define input fields			%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

buttons = uibuttongroup('Position', [.2 .05 .54 .18],...
	'visible','on');

	textDim = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.01 .71 .2 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Dimension:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The order is the number of points forming the OPs');

	textTau = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.01 .51 .2 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Delay:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The delay is the distance between the points forming the OPs');

	textWindowSize = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.01 .31 .2 .18],...
		'BackgroundColor', [0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Window size :',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The size of the shifting window.');

	textStepSize = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.01 .11 .2 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Step size :',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The number of steps by which the window is shifted.');

	valDim = uicontrol('Parent',buttons,...
		'Tag','valDim',...
		'Units', 'normalized', ...
		'Position', [.275 .71 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(dim),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Insert the dimension (2-13)');	

	valTau = uicontrol('Parent',buttons,...
		'Tag','valTau',...
		'Units', 'normalized', ...
		'Position', [.275 .51 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(tau),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Insert the time delay. Choose 0 for automatic estimation');	
		
	valWindowSize= uicontrol('Parent',buttons,...
		'Tag','valWindowSize',...
		'Units', 'normalized', ...
		'Position', [.275 .31 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(ws),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Insert the window size.');

	valStepSize = uicontrol('Parent',buttons,...
		'Tag','valStepSize',...
		'Units', 'normalized',...
		'Position', [.275 .11 .125 .18],...
		'BackgroundColor',[.801 .75 .688],...
		'Style','edit',... 
		'String',num2str(ss),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Insert the step size.');

	textMinDiag = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.45 .71 .25 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','min. diag. length:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The minimal length of diagonal lines to be quantified');

	textMinVert = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.45 .51 .25 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','min. vert. length:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The minimal length of vertical lines to be quantified');

	textTheiler = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.45 .31 .25 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','theiler:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The size of the theiler window.');

	textPlotSize = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.45 .11 .25 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','RP mode:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Adjust the size of the RP to match pattern length.');

	valMinDiag = uicontrol('Parent',buttons,...
		'Tag','valMinDiag',...
		'Units', 'normalized', ...
		'Position', [.75 .71 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(minDiag),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Enter the minimal length of diagonal lines.');	

	valMinVert = uicontrol('Parent',buttons,...
		'Tag','valMinVert',...
		'Units', 'normalized', ...
		'Position', [.75 .51 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(minVert),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Enter the minimal length of vertical lines.');	

	valTheiler = uicontrol('Parent',buttons,...
		'Tag','valTheiler',...
		'Units', 'normalized', ...
		'Position', [.75 .31 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(theiler),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Enter the size of the Theiler Window.');	
		
	valPlotSize = uicontrol('Parent',buttons,...
		'Tag','valPlotSize',...
		'Units', 'normalized',...
		'Position', [.75 .11 .15 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','popupmenu',...
    'String',{'small','full'},...
		'Value',valPlotSizeValue,...
		'Tooltip','Choose small to be compatible with CRPtool or full to adjust for pattern size');		

		
%%%%%%%%%%%%%%%%%%%%%%%%%
%			Define buttons 		%
%%%%%%%%%%%%%%%%%%%%%%%%%

	buttonStore = uicontrol('Parent',fHandle, ...
		'Units', 'normalized', ...
		'Position', [.75 .17 .15 .06],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Store',...
		'Visible','on', ...
		'Tooltip','Store the rqa measures entropy vector.',...
		'Callback',{@buttonStoreCallback});

	buttonClose = uicontrol('Parent',fHandle, ...
		'Units', 'normalized', ...
		'Position', [.75 .11 .15 .06],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Close',...
		'Visible','on', ...
		'Tooltip','Close the GUI',...
		'Callback',{@buttonCloseCallback});

	buttonCompute = uicontrol('Parent',fHandle,...
		'Tag','buttonCompute',...
		'Units', 'normalized',...
		'Position', [.75 .05 .15 .06],...
		'BackgroundColor',[.801 .75 .688],...
		'Style','pushbutton',... 
		'String','Compute',...
		'FontWeight','bold',...
		'Visible','on', ...
		'Callback',{@buttonComputeCallback,X},...
		'Tooltip','Start the computation');

%%%%%%%%%%%%%%%%%%%%%%%
%			fancy stuff 		%
%%%%%%%%%%%%%%%%%%%%%%%

	textNLD = uicontrol('Parent',fHandle,...
		'Units', 'normalized', ...
		'Position',[.025 .1 .15 .1],...
		'Style','text',... 
		'BackgroundColor',[.801 .75 .688], ... 
		'Tag', 'NLD ',...
		'FontSize',9,...
		'String',sprintf('Nonlinear Dynamics Group\n University of Potsdam\n (c) 2007'),...
		'ToolTip','The Nonlinear Dynamics Group http://www.agnld.uni-potsdam.de',...
		'HorizontalAlignment','center');
