  %%%%%%%%%%%%%%%%%%%%%%%
%			Define axes			%
%%%%%%%%%%%%%%%%%%%%%%%

axSurf = axes('Parent',figHandle,...
	'Position',[.1 .3 .8 .65],...
	'Tag', 'axSurf',...
	'NextPlot','replace',...
	'Box','on',...
	'Xtick',[],...
	'YTick',[]);

%%%%%%%%%%%%%%%%%%%%%%%
%  Define colourbar		%
%%%%%%%%%%%%%%%%%%%%%%%

hColourbar = colorbar('Location','South',...
	'Position',[.1 .2 .8 .025],...
	'YTick',[],...
	'YTickMode','manual',...
	'XTick',[],...
	'XTickMode','manual',...
	'Box','on',...
	'Tag','Colourbar');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			Define input fields			%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

buttons = uibuttongroup('Position', [.2 .05 .14 .1],...
	'visible','on');

	textDim = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.05 .5 .6 .3],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Dimension:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The dimension/order is the number of points forming the OPs');

	textTau = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.05 .1 .6 .3],...
		'BackgroundColor', [0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Delay :',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The distance between the points forming the order patterns.If none provided it is estimated for every individual trial');

	valDim = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.7 .5 .2 .3],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(dim),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tag','valDim',...
		'Tooltip','Insert the dimension/order (2-13)');	

	valTau = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.7 .1 .2 .3],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(tau),...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tag','valTau',...
		'Tooltip','Insert the time delay.');

%%%%%%%%%%%%%%%%%%%%%%%%%
%			colourmap group		%
%%%%%%%%%%%%%%%%%%%%%%%%%

buttons2 = uibuttongroup('Position', [.35 .05 .2 .1],...
	'visible','on');

	textColourChooser = uicontrol('Parent',buttons2, ...
		'Units', 'normalized', ...
		'Position', [.1 .6 .8 .3],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Select Colourmap:',...
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Tooltip','Choose the colourmap you would like to use');

	colourMaps = {'hsv','hot','gray','bone','copper',...
		'pink','white','flag','lines',...
		'jet','prism','cool','autumn','spring',...
		'winter','summer'};
		
	valColourMap = uicontrol('Parent',buttons2,...
		'Units', 'normalized', ...
		'Position',[.1 .2 .8 .3],...
		'Style','popupmenu',...
    	'String',colourMaps,...
		'Tag','valColourMap',...
		'Value',11);
		
%%%%%%%%%%%%%%%%%%%%%%%%%
%			Define buttons 		%
%%%%%%%%%%%%%%%%%%%%%%%%%

	buttonStore = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.57 .1 .12 .05],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Store',...
		'Visible','on', ...
		'Tooltip','Store the opgram matrix.');

	buttonClose = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.57 .05 .12 .05],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Close',...
		'Visible','on', ...
		'Tooltip','Close the GUI');

	buttonTranscode = uicontrol('Parent',figHandle,...
		'Units', 'normalized',...
		'Position', [.7 .1 .1 .05],...
		'BackgroundColor',[.801 .75 .688],...
		'Style','pushbutton',... 
		'String','Transcode',...
		'Tag','buttonTranscode',...
		'Enable','Off',...
		'FontWeight','bold',...
		'Visible','on', ...
		'Tooltip','Transcode Pattern into 3-Symbol distribution.');

	buttonReversi = uicontrol('Parent',figHandle,...
		'Units', 'normalized',...
		'Position', [.7 .05 .1 .05],...
		'BackgroundColor',[.801 .75 .688],...
		'Style','pushbutton',... 
		'String','Reversi',...
		'Tag','buttonReversi',...
		'Enable','Off',...
		'FontWeight','bold',...
		'Visible','on', ...
		'Tooltip','Perform meanfield transformation.');

	buttonCompute = uicontrol('Parent',figHandle,...
		'Units', 'normalized',...
		'Position', [.8 .05 .1 .1],...
		'BackgroundColor',[.801 .75 .688],...
		'Style','pushbutton',... 
		'String','Compute',...
		'FontWeight','bold',...
		'Visible','on', ...
		'Tooltip','Start the computation');

%%%%%%%%%%%%%%%%%%%%%%%
%			fancy stuff 		%
%%%%%%%%%%%%%%%%%%%%%%%

	textNLD = uicontrol('Parent',figHandle,...
		'Units', 'normalized', ...
		'Position',[.01 .05 .19 .1],...
		'Style','text',... 
		'BackgroundColor',[.801 .75 .688], ... 
		'Tag', 'NLD ',...
		'FontSize',9,...
		'String',sprintf('Nonlinear Dynamics Group \n University of Potsdam\n (c) 2007'),...
		'ToolTip','The Nonlinear Dynamics Group http://www.agnld.uni-potsdam.de');
