%%%%%%%%%%%%%%%%%%%%%%%
%			Define axes			%
%%%%%%%%%%%%%%%%%%%%%%%

axSurf = axes('Parent',figHandle,...
	'Position',[.05 .3 .9 .65],...
	'Tag', 'axSurf',...
	'NextPlot','replace',...
	'Box','on',...
	'Xtick',[],...
	'Ytick',[]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%			Define input fields			%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

buttons = uibuttongroup('Position', [.05 .05 .49 .18],...
	'visible','on');

	textDim = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.01 .71 .2 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Dimension:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The order is the number of points forming the OPs');

	textTau = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.01 .51 .2 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Delay:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The delay is the distance between the points forming the OPs');

	textWindowSize = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.01 .31 .2 .18],...
		'BackgroundColor', [0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Window size :',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The size of the shifting window.');

	textStepSize = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.01 .11 .2 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Step size :',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The number of steps by which the window is shifted.');

	valDim = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.275 .71 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(dim),...
		'Tag','valDim',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Insert the dimension (2-13)');	

	valTau = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.275 .51 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(tau),...
		'Tag','valTau',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Insert the time delay');	
		
	valWindowSize= uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.275 .31 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(ws),...
		'Tag','valWindowSize',...		
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Insert the window size.');

	valStepSize = uicontrol('Parent',buttons,...
		'Units', 'normalized',...
		'Position', [.275 .11 .125 .18],...
		'BackgroundColor',[.801 .75 .688],...
		'Style','edit',... 
		'String',num2str(ss),...
		'Tag','valStepSize',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Insert the step size.');

	textTheiler = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.45 .71 .25 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Theiler window:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The size of the theiler window.');
		
	textMinDiag = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.45 .51 .25 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','min. diag. length:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The minimal length of diagonal lines to be quantified');

	textMinVert = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.45 .31 .25 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','min. vert. length:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','The minimal length of vertical lines to be quantified');

	textPlotSize = uicontrol('Parent',buttons, ...
		'Units', 'normalized', ...
		'Position', [.45 .11 .25 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','RP mode:',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Adjust the size of the RP to match pattern length.');

	valTheiler = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.75 .71 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(theiler),...
		'Tag','valTheiler',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Enter the size of the Theiler Window.');	
		
	valMinDiag = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.75 .51 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(minDiag),...
		'Tag','valMinDiag',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Enter the minimal length of diagonal lines.');	

	valMinVert = uicontrol('Parent',buttons,...
		'Units', 'normalized', ...
		'Position', [.75 .31 .125 .18],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','edit',... 
		'String',num2str(minVert),...
		'Tag','valMinVert',...
		'HorizontalAlignment','right',...
		'Visible','on',...
		'Tooltip','Enter the minimal length of vertical lines.');	
		
	valPlotSize = uicontrol('Parent',buttons,...
		'Units', 'normalized',...
		'Position', [.75 .11 .15 .18],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','popupmenu',...
    'String',{'small','full'},...
		'Tag','valPlotSize',...
		'Value',valPlotSizeValue,...
		'Tooltip','Choose small to be compatible with CRPtool or full to adjust for pattern size');		

%%%%%%%%%%%%%%%%%%%%%%%%%
%			colourmap group		%
%%%%%%%%%%%%%%%%%%%%%%%%%

buttons2 = uibuttongroup('Position', [.55 .05 .2 .18],...
	'visible','on');

	textMeasureChooser = uicontrol('Parent',buttons2, ...
		'Units', 'normalized', ...
		'Position', [.1 .75 .8 .2],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Select RQA measure:',...
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Tooltip','Choose the rqa measure you would like to plot');

	valMeasureChooser = uicontrol('Parent',buttons2,...
		'Units', 'normalized', ...
		'Position',[.1 .55 .8 .2],...
		'Style','popupmenu',...
    'String',measures,...
		'Tag','valMeasureChooser',...
		'Value',1,...
		'Callback',{@valMeasureChooserCallback,tScale,measures});		

	textColourChooser = uicontrol('Parent',buttons2, ...
		'Units', 'normalized', ...
		'Position', [.1 .3 .8 .2],...
		'BackgroundColor',[0.7020 0.7020 0.7020], ...
		'Style','text',... 
		'String','Select Colourmap:',...
		'HorizontalAlignment','left',...
		'Visible','on',...
		'Tooltip','Choose the colourmap you would like to use');

	valColourMap = uicontrol('Parent',buttons2,...
		'Units', 'normalized', ...
		'Position',[.1 .1 .8 .2],...
		'Style','popupmenu',...
    	'String',colourMaps,...
		'Tag','valColourMap',...
		'Value',11,...
		'Callback',{@valColourMapCallback,colourMaps});

		
%%%%%%%%%%%%%%%%%%%%%%%%%
%	Define buttons 		%
%%%%%%%%%%%%%%%%%%%%%%%%%

	buttonStore = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.76 .17 .19 .06],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Store',...
		'Visible','on', ...
		'Tooltip','Store the rqa image array.',...
		'Callback',{@buttonStoreCallback});

	buttonClose = uicontrol('Parent',figHandle, ...
		'Units', 'normalized', ...
		'Position', [.76 .11 .19 .06],...
		'BackgroundColor',[.801 .75 .688], ...
		'Style','pushbutton',... 
		'String','Close',...
		'Visible','on', ...
		'Tooltip','Close the GUI',...
		'Callback',{@buttonCloseCallback});

	buttonCompute = uicontrol('Parent',figHandle,...
		'Units', 'normalized',...
		'Position', [.76 .05 .19 .06],...
		'BackgroundColor',[.801 .75 .688],...
		'Style','pushbutton',... 
		'String','Compute',...
		'FontWeight','bold',...
		'Visible','on', ...
		'Tooltip','Start the computation',...
		'Callback',{@buttonComputeCallback,X,measures,colourMaps,tScale});

%%%%%%%%%%%%%%%%%%%%%%%
%			fancy stuff 		%
%%%%%%%%%%%%%%%%%%%%%%%

	textNLD = uicontrol('Parent',figHandle,...
		'Units', 'normalized', ...
		'Position',[.1 .01 .85 .03],...
		'Style','text',... 
		'BackgroundColor',[.801 .75 .688], ... 
		'Tag', 'NLD ',...
		'FontSize',9,...
		'String',sprintf('Nonlinear Dynamics Group University of Potsdam (c) 2007'),...
		'ToolTip','The Nonlinear Dynamics Group http://www.agnld.uni-potsdam.de',...
		'HorizontalAlignment','right');
